import './globals.css';
import { Inter } from 'next/font/google';
import { UserProvider } from '@/context/UserContext'; // Asegúrate de importar correctamente
import Navbar from '@/components/Navbar';
import Contacts from '@/components/Contacts';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <div>
            <Contacts />
            <Navbar />
            <main>{children}</main>
            <Footer />
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
